java tlc.TLC -cleanup  etest1
java tlc.TLC -cleanup  etest2
java tlc.TLC -cleanup  etest3
java tlc.TLC -cleanup  etest4
java tlc.TLC -cleanup  etest5
java tlc.TLC -cleanup  etest6
java tlc.TLC -cleanup  etest7
java tlc.TLC -cleanup  etest8
java tlc.TLC -cleanup  etest9
java tlc.TLC -cleanup  etest10
java tlc.TLC -cleanup  etest11
java tlc.TLC -cleanup  etest12
java tlc.TLC -cleanup  etest13
java tlc.TLC -cleanup  etest14
java tlc.TLC -cleanup  etest15
java tlc.TLC -cleanup  etest16
